name: 'container'

on:
    push:
    workflow_dispatch:
    schedule:
        -   cron: '0 7 * * MON'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v1

            -   name: Inject slug/short variables
                uses: rlespinasse/github-slug-action@v2.x

            -   name: Get build time
                uses: 1466587594/get-current-time@v1
                id: current-time

            -   name: docker registry login
                run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

            -   name: Build docker image
                run: |
                    docker build \
                    --build-arg BUILD_DATE=${{ steps.current-time.outputs.time }} \
                    --build-arg VCS_REF=${{ env.GITHUB_SHA_SHORT }} \
                    -t "ghcr.io/${{ github.repository }}:latest" .

            -   name: docker push
                run: docker push ghcr.io/${{ github.repository }}:latest
